#pragma once

#include <cstdint> // for int32_t, uint16_t
#include <string>  // for string
#include <utility> // for pair
#include <vector>  // for vector

namespace vp
{

struct Rectangle
{
    int32_t northLimit;
    int32_t southLimit;
    int32_t eastLimit;
    int32_t westLimit;
};

std::string getCountryCodeFromLatLon(float latitude, float longitude, const std::string &country_db_path);
bool insidePolygonIndicator(const std::vector<std::pair<int32_t, int32_t>> &locations,
                            int32_t current_location_latitude, int32_t current_location_Longitude);
bool polygonInsidePolygonIndicator(const std::vector<std::pair<int32_t, int32_t>> &locations, const std::vector<std::pair<int32_t, int32_t>> &otherlocations);
bool insideRectangleIndicator(const std::vector<Rectangle> &rectangles,
                              int32_t current_location_latitude, int32_t current_location_Longitude);

bool circleInsidePolygon(const std::vector<std::pair<int32_t, int32_t>> &locations, int32_t center_lat, int32_t center_lon, double radius_m);
bool circleInsideCountryAt(int32_t center_lat, int32_t center_lon, uint16_t m49_country_code, double radius_m, const std::string &country_db_path, double radius_padding_m, double promote_threshold_m);

inline std::string m49ToAlpha3(const uint16_t &m49_code)
{
    switch (m49_code)
    {
    case 4:
        return "AFG";
    case 248:
        return "ALA";
    case 8:
        return "ALB";
    case 12:
        return "DZA";
    case 16:
        return "ASM";
    case 20:
        return "AND";
    case 24:
        return "AGO";
    case 660:
        return "AIA";
    case 10:
        return "ATA";
    case 28:
        return "ATG";
    case 32:
        return "ARG";
    case 51:
        return "ARM";
    case 533:
        return "ABW";
    case 36:
        return "AUS";
    case 40:
        return "AUT";
    case 31:
        return "AZE";
    case 44:
        return "BHS";
    case 48:
        return "BHR";
    case 50:
        return "BGD";
    case 52:
        return "BRB";
    case 112:
        return "BLR";
    case 56:
        return "BEL";
    case 84:
        return "BLZ";
    case 204:
        return "BEN";
    case 60:
        return "BMU";
    case 64:
        return "BTN";
    case 68:
        return "BOL";
    case 535:
        return "BES";
    case 70:
        return "BIH";
    case 72:
        return "BWA";
    case 74:
        return "BVT";
    case 76:
        return "BRA";
    case 86:
        return "IOT";
    case 92:
        return "VGB";
    case 96:
        return "BRN";
    case 100:
        return "BGR";
    case 854:
        return "BFA";
    case 108:
        return "BDI";
    case 132:
        return "CPV";
    case 116:
        return "KHM";
    case 120:
        return "CMR";
    case 124:
        return "CAN";
    case 136:
        return "CYM";
    case 140:
        return "CAF";
    case 148:
        return "TCD";
    case 152:
        return "CHL";
    case 156:
        return "CHN";
    case 344:
        return "HKG";
    case 446:
        return "MAC";
    case 162:
        return "CXR";
    case 166:
        return "CCK";
    case 170:
        return "COL";
    case 174:
        return "COM";
    case 178:
        return "COG";
    case 184:
        return "COK";
    case 188:
        return "CRI";
    case 384:
        return "CIV";
    case 191:
        return "HRV";
    case 192:
        return "CUB";
    case 531:
        return "CUW";
    case 196:
        return "CYP";
    case 203:
        return "CZE";
    case 408:
        return "PRK";
    case 180:
        return "COD";
    case 208:
        return "DNK";
    case 262:
        return "DJI";
    case 212:
        return "DMA";
    case 214:
        return "DOM";
    case 218:
        return "ECU";
    case 818:
        return "EGY";
    case 222:
        return "SLV";
    case 226:
        return "GNQ";
    case 232:
        return "ERI";
    case 233:
        return "EST";
    case 748:
        return "SWZ";
    case 231:
        return "ETH";
    case 238:
        return "FLK";
    case 234:
        return "FRO";
    case 242:
        return "FJI";
    case 246:
        return "FIN";
    case 250:
        return "FRA";
    case 254:
        return "GUF";
    case 258:
        return "PYF";
    case 260:
        return "ATF";
    case 266:
        return "GAB";
    case 270:
        return "GMB";
    case 268:
        return "GEO";
    case 276:
        return "DEU";
    case 288:
        return "GHA";
    case 292:
        return "GIB";
    case 300:
        return "GRC";
    case 304:
        return "GRL";
    case 308:
        return "GRD";
    case 312:
        return "GLP";
    case 316:
        return "GUM";
    case 320:
        return "GTM";
    case 831:
        return "GGY";
    case 324:
        return "GIN";
    case 624:
        return "GNB";
    case 328:
        return "GUY";
    case 332:
        return "HTI";
    case 334:
        return "HMD";
    case 336:
        return "VAT";
    case 340:
        return "HND";
    case 348:
        return "HUN";
    case 352:
        return "ISL";
    case 356:
        return "IND";
    case 360:
        return "IDN";
    case 364:
        return "IRN";
    case 368:
        return "IRQ";
    case 372:
        return "IRL";
    case 833:
        return "IMN";
    case 376:
        return "ISR";
    case 380:
        return "ITA";
    case 388:
        return "JAM";
    case 392:
        return "JPN";
    case 832:
        return "JEY";
    case 400:
        return "JOR";
    case 398:
        return "KAZ";
    case 404:
        return "KEN";
    case 296:
        return "KIR";
    case 414:
        return "KWT";
    case 417:
        return "KGZ";
    case 418:
        return "LAO";
    case 428:
        return "LVA";
    case 422:
        return "LBN";
    case 426:
        return "LSO";
    case 430:
        return "LBR";
    case 434:
        return "LBY";
    case 438:
        return "LIE";
    case 440:
        return "LTU";
    case 442:
        return "LUX";
    case 450:
        return "MDG";
    case 454:
        return "MWI";
    case 458:
        return "MYS";
    case 462:
        return "MDV";
    case 466:
        return "MLI";
    case 470:
        return "MLT";
    case 584:
        return "MHL";
    case 474:
        return "MTQ";
    case 478:
        return "MRT";
    case 480:
        return "MUS";
    case 175:
        return "MYT";
    case 484:
        return "MEX";
    case 583:
        return "FSM";
    case 492:
        return "MCO";
    case 496:
        return "MNG";
    case 499:
        return "MNE";
    case 500:
        return "MSR";
    case 504:
        return "MAR";
    case 508:
        return "MOZ";
    case 104:
        return "MMR";
    case 516:
        return "NAM";
    case 520:
        return "NRU";
    case 524:
        return "NPL";
    case 528:
        return "NLD";
    case 540:
        return "NCL";
    case 554:
        return "NZL";
    case 558:
        return "NIC";
    case 562:
        return "NER";
    case 566:
        return "NGA";
    case 570:
        return "NIU";
    case 574:
        return "NFK";
    case 807:
        return "MKD";
    case 580:
        return "MNP";
    case 578:
        return "NOR";
    case 512:
        return "OMN";
    case 586:
        return "PAK";
    case 585:
        return "PLW";
    case 591:
        return "PAN";
    case 598:
        return "PNG";
    case 600:
        return "PRY";
    case 604:
        return "PER";
    case 608:
        return "PHL";
    case 612:
        return "PCN";
    case 616:
        return "POL";
    case 620:
        return "PRT";
    case 630:
        return "PRI";
    case 634:
        return "QAT";
    case 410:
        return "KOR";
    case 498:
        return "MDA";
    case 638:
        return "REU";
    case 642:
        return "ROU";
    case 643:
        return "RUS";
    case 646:
        return "RWA";
    case 652:
        return "BLM";
    case 654:
        return "SHN";
    case 659:
        return "KNA";
    case 662:
        return "LCA";
    case 663:
        return "MAF";
    case 666:
        return "SPM";
    case 670:
        return "VCT";
    case 882:
        return "WSM";
    case 674:
        return "SMR";
    case 678:
        return "STP";
    case 682:
        return "SAU";
    case 686:
        return "SEN";
    case 688:
        return "SRB";
    case 690:
        return "SYC";
    case 694:
        return "SLE";
    case 702:
        return "SGP";
    case 534:
        return "SXM";
    case 703:
        return "SVK";
    case 705:
        return "SVN";
    case 90:
        return "SLB";
    case 706:
        return "SOM";
    case 710:
        return "ZAF";
    case 239:
        return "SGS";
    case 728:
        return "SSD";
    case 724:
        return "ESP";
    case 144:
        return "LKA";
    case 275:
        return "PSE";
    case 729:
        return "SDN";
    case 740:
        return "SUR";
    case 744:
        return "SJM";
    case 752:
        return "SWE";
    case 756:
        return "CHE";
    case 760:
        return "SYR";
    case 762:
        return "TJK";
    case 764:
        return "THA";
    case 626:
        return "TLS";
    case 768:
        return "TGO";
    case 772:
        return "TKL";
    case 776:
        return "TON";
    case 780:
        return "TTO";
    case 788:
        return "TUN";
    case 792:
        return "TUR";
    case 795:
        return "TKM";
    case 796:
        return "TCA";
    case 798:
        return "TUV";
    case 800:
        return "UGA";
    case 804:
        return "UKR";
    case 784:
        return "ARE";
    case 826:
        return "GBR";
    case 834:
        return "TZA";
    case 581:
        return "UMI";
    case 840:
        return "USA";
    case 850:
        return "VIR";
    case 858:
        return "URY";
    case 860:
        return "UZB";
    case 548:
        return "VUT";
    case 862:
        return "VEN";
    case 704:
        return "VNM";
    case 876:
        return "WLF";
    case 732:
        return "ESH";
    case 887:
        return "YEM";
    case 894:
        return "ZMB";
    case 716:
        return "ZWE";
    default:
        return "";
    }
}

} // namespace vp